hydra:
  run:
    dir: ckpts/${model.name}_${model.mel_spec.mel_spec_type}${model.tokenizer}/${now:%Y-%m-%d}/${now:%H-%M-%S}

datasets:
  name: train_dataset_emilia
  dataset_type: OnlineLance
  batch_size_per_gpu: 2000  # 8 GPUs, 8 * 38400 = 307200
  batch_size_type: frame  # "frame" or "sample"
  max_samples: 32 # max sequences per batch if use frame-wise batch_size. we set 32 for small models, 64 for base models
  num_workers: 4  # num_workers for dataloader 

optim:
  epochs: 20
  learning_rate: 7.5e-5
  num_warmup_updates: 20000  # warmup updates
  grad_accumulation_steps: 2  # note: updates = steps / grad_accumulation_steps 
  max_grad_norm: 1.0  # gradient clipping
  bnb_optimizer: False  # use bnb 8bit AdamW optimizer or not

# 159.252624 M  768 16
model:
  name: fm_10ms_contrasive_ecapa_pmeanflow  # model name
  tokenizer: cosyvoice2 # tokenizer type
  feat: meanflow_pimproved  # if tokenizer = 'custom', define the path to the tokenizer you want to use (should be vocab.txt)
  text_num_embeds: 6563
  arch:
    dim: 768
    depth: 16    
    heads: 16
    ff_mult: 2
    text_dim: 512
    conv_layers: 4
    checkpoint_activations: False  # recompute activations and save memory for extra compute
  mel_spec:
    target_sample_rate: 16000
    n_mel_channels: 80
    hop_length: 160
    win_length: 640
    n_fft: 1024
    mel_spec_type: hifigan  # 'vocos' or 'bigvgan'
  vocoder:
    is_local: False  # use local offline ckpt or not
    local_path: None  # local vocoder path

ckpts:
  logger: tensorboard  # wandb | tensorboard | None
  save_per_updates: 10000  # save checkpoint per updates
  keep_last_n_checkpoints: -1  # -1 to keep all, 0 to not save intermediate, > 0 to keep last N checkpoints
  last_per_updates: 5000  # save last checkpoint per updates
  save_dir: ckpts/${model.name}_${model.mel_spec.mel_spec_type}${model.tokenizer}
